about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('', views.about, name='about'),
]

authentication/urls.py
from django.urls import path
from . import views

app_name = "authentication"

urlpatterns = [
    path('SignIn/', views.SignIn, name='SignIn'),
    path('SignOut/', views.SignOut, name='SignOut')
]

books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.books, name='books'),
    path('volumes/',views.search, name='search')
]

status/urls.py
from django.urls import path
from . import views

app_name = 'status'

urlpatterns = [
    path('', views.status, name='status'),
]

story6/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('status.urls')),
    path('about/', include('about.urls')),
    path('books/', include('books.urls')),
    path('authentication/', include('authentication.urls')),
]

about/models.py
from django.db import models

# Create your models here.

authentication/models.py
from django.db import models

# Create your models here.

books/models.py
from django.db import models

# Create your models here.

status/models.py
from django.db import models

class create_status(models.Model):
    statusfield = models.CharField(max_length=300)
    time = models.DateTimeField()

    def __str__(self):
        return self.statusfield

about/views.py
from django.shortcuts import render

def about(request):
    return render(request, 'about.html')

authentication/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login as auth_SignIn, logout as auth_SignOut

def SignIn(request):
    if request.user.is_authenticated:
        return redirect('status:status')
    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_SignIn(request, user)
                request.session['username'] = user.first_name
                return redirect('status:status')
            else:
                return render(request, 'SignIn.html', {
                        'error' : 'invalid username or password'
                    }
                )
    return render(request, 'SignIn.html')

def SignOut(request):
    auth_SignOut(request)
    return redirect('status:status')

books/views.py
from django.http import HttpResponseForbidden, JsonResponse
from django.shortcuts import render
import json
import requests


def books(request):
    return render(request, 'books.html')

def search(request):
    url = 'https://www.googleapis.com/books/v1/volumes'
    url +=  f"?maxResults={10}&q={request.GET.get('q')}"
    data = requests.get(url).json()
    return JsonResponse(data, json_dumps_params={'indent': 2})

status/views.py
from django.shortcuts import render, redirect
from .models import create_status
import datetime

def status(request):
    all_status=create_status.objects.all().order_by('time')
    context= {'all_status': all_status}
    if request.method == 'POST':
        status=create_status()
        status.statusfield=request.POST.get('statusfield')
        status.time=datetime.datetime.now()
        status.save()
        return render(request, 'status.html',context)
    else:
        return render(request, 'status.html',context)

about/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}about{% endblock title %}

{% block content %}

    <div class="about">
    <div class="container mt-5 about">
        <img src="{% static 'assets/myphoto.jpg' %}"  class="rounded-circle float-center">
        <h3>Audrey Annisa Datau</h3>
        <p>My name is Audrey Annisa Datau and you can call me 
                Audrey. I was born <br> and grew up  in Jakarta, Indonesia.
                 I am a hardworking and punctual individual<br> with passion
                for technology. I work well in team and also on my own. <br> 
                I am well organized and love to make plans about things 
                that i will do.
        </p> 
    </div>
    </div>

    <div class="wrapper">
            <div class="accordion active activity">
              <div class="accordion_tab active">
                  Activity
                  <div class="accordion_arrow">
                    <img src="https://i.imgur.com/PJRz0Fc.png" alt="arrow">
                </div>
              </div>
              <div class="accordion_content">
                <div class="accordion_item">
                  <p class="item_title">Teaching Assistant for Programming Foundation 1</p>
                  <p>
                   <strong>Universitas Indonesia
                    <br> September 2019 - present</strong>
                    <br> Help and make students comfortable with programming, arranging tutorial problems, scoring students tutorial and assignments.
                  </p>
                </div>
              </div>
            </div>
            <div class="accordion experience">
              <div class="accordion_tab">
                  Experience
                  <div class="accordion_arrow">
                    <img src="https://i.imgur.com/PJRz0Fc.png" alt="arrow">
                </div>
              </div>
              <div class="accordion_content">
                <div class="accordion_item">
                  <p class="item_title">BEM Fasilkom UI</p>
                  <p>
                    <strong>Public Relations Staff
                         <br> February 2019 - December 2019 </strong>
                         <br> Maintain the publication of BEM Fasilkom UI in social media  and be a liason between
                         <br> BEM & external parties both inside and outside faculty.
                       </p>
                </div>
                <div class="accordion_item">
                  <p class="item_title">COMPFEST</p>
                  <p>
                    <strong>Marketing Staff
                    <br> March 2019 - September 2019 </strong>
                    <br> Maintain all social media of COMPFEST. 
                </p>
                </div>
                <div class="accordion_item">
                    <p class="item_title">CROPS PATRIOTS</p>
                    <p>
                    <strong>Vice Project Officer
                    <br> April 2017</strong>
                    <br> Be the right handman for the project officer.
                </p>
                </div>
              </div>
            </div>
            <div class="accordion achievment">
              <div class="accordion_tab">
                  Achievment
                  <div class="accordion_arrow">
                    <img src="https://i.imgur.com/PJRz0Fc.png" alt="arrow">
                </div>
              </div>
              <div class="accordion_content">
                <div class="accordion_item">
                  <p class="item_title">PPI 2016</p>
                  <p>Became one of the students who had served as a member of National Flag Hoisting Troop on the commemoration of the Republic of Indonesia's Independence Day at the city level.</p>
                </div>
              </div>
            </div>
          </div>
    
  {% endblock content %}

authentication/templates/SignIn.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Sign In{% endblock title %}

{% block content %}
<div class="SignIn">
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="user_card">
                <div class="d-flex justify-content-center">
                    <div class="brand_logo_container">
                        <img src="{% static 'assets/title.png' %}" class="brand_logo" alt="Logo">
                    </div>
                </div>
                <div class="d-flex justify-content-center form_container">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <input type="text" name="username" class="form-control input_user" value="" placeholder="username">
                        </div>
                        <div class="input-group mb-2">
                            <input type="password" name="password" class="form-control input_pass" value="" placeholder="password">
                        </div>
                            <div class="d-flex justify-content-center mt-3 login_container">
                     <button type="submit" name="button" class="btn login_btn">Sign In</button>
                   </div>
                    </form>
                </div>
                {% if error %}
                <div class="alert alert-warning alert-dismissible fade show">
                    <strong>Warning!</strong> {{ error }}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

books/templates/books.html
{% extends 'base.html' %}
{% load static %}

{% block title %}books{% endblock title %}

{% block content %}
<div class="allcontent">
        <form method="GET" class="form" action="volumes">
            {% csrf_token %}
         <div class="form-group">
            {% if user.is_authenticated %}
            <label for="status" class="labelsearch">Hey {{ request.user.first_name }}, search books that you want to know the details!</label>
            {% else %}
            <label for="status" class="labelsearch">Search Books</label>
            {% endif %}
     
             <input type="text" class="form-control"  id="searchfield" placeholder="search your books" name="searchfield">
         </div>
         <button type="submit" class="btn btn-primary" id='submit'>Search</button>
        </form>
    </div>

    <div class="container mt-5">
      <h1 class="keyword-results">Results</h1>
    </div>

    <div id="book-results-table" class="table-responsive">
        <div class="container mt-5">
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th class="align-middle" scope="col">No.</th>
              <th class="align-middle" scope="col">Book Information</th>
              <th class="align-middle" scope="col">Cover</th>
            </tr>
          </thead>
          <tbody id="results">
          </tbody>
        </table>
      </div>
    </div>
{% endblock content %}
{% block custom_scripts %}
<script src="{% static 'js/books.js' %}"> </script>
{% endblock custom_scripts %}

status/templates/status.html
{% extends 'base.html' %}

{% block title %}status{% endblock title %}

{% block content %}
    {% if user.is_authenticated %}
    <h2>Hey {{ request.user.first_name }}, how are you?</h2>
    {% else %}
    <h2>Hey, how are you?</h2>
    {% endif %}

   <div class="allcontent">
   <form method="POST" class="form">
       {% csrf_token %}
    <div class="form-group">
        <label for="status" class="labelstatus">status </label>
        <input type="text" class="form-control"  id="statusfield" placeholder="fill with your status" name="statusfield">
    </div>
    <button type="submit" class="btn btn-primary" id='submit'>Submit</button>
   </form>
    </div>

    <div class="table_data" id="table_data">
    <div class="container mt-5">
    <h3>List of status</h3>
    <table class="table table-hover" id="table">
    <thead>
    <tr>
        <th scope="col">No</th>
        <th scope="col">Status</th>
        <th scope="col">Date/time</th>
    </tr>
    </thead>
    <div class="contentstatus">
        <tbody>
        {% for s in all_status %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ s.statusfield }}</td>
                <td>{{ s.time }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </div>
    </table>
    </div>
    </div>

{% endblock content %}

templates/base.html
{% load static %}
<html>
    <head>
        <title>{% block title %}{% endblock title %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- menambahkan icon -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

         <!-- menghubungkan dengan css dan bootstrap -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="Stylesheet" href="{% static 'css/status.css' %}">

        <!-- membuat icon judul website-->
        <link rel="icon" href="{% static 'assets/title.png' %}" type="image/icon">

        <!-- menggunakan jenis font yang sesuai -->
        <link href="https://fonts.googleapis.com/css?family=Racing+Sans+One&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Nunito&display=swap" rel="stylesheet">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="{% static 'js/status.js' %}"> </script>


    </head>

    <body>
    
    <div id="navbarcolor">
    <nav class="navbar navbar-expand-sm navbar-dark">
        <!-- Brand -->
        <a class="navbar-brand" href="#"><img src="{% static 'assets/title.png' %}" width="20" height="20"></a>
        
        <!-- Links -->
        <ul class="navbar-nav">
            <li class="nav-item">
            <a class="nav-link" href="{% url 'status:status' %}" id="text-nav-status">Status</a>
            </li>
            <li class="nav-item">
                <a  class="nav-link" href="{% url 'about:about' %}" id="text-nav-about">About</a>
            </li>
            <li class="nav-item">
                <a  class="nav-link" href="{% url 'books:books' %}" id="text-nav-books">Books</a>
            </li>
            
        
            <!-- Dropdown -->
            <li class="nav-item dropdown">
            <a id="text-nav-theme" class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                Change Theme
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item"  onclick="changeThemeGreen()">Green</a>
                <a class="dropdown-item"  onclick="changeThemeMonochrome()">Monochrome</a>
            </div>
            </li>
            <div id="log-button" class="nav-item mx-2 my-2 my-md-0">
                {% if user.is_authenticated %}
                <a class="btn btn-primary" href="{% url 'authentication:SignOut' %}" id="text-nav-oauth">Sign Out</a>
                {% else %}
                <a class="btn btn-primary" href="{% url 'authentication:SignIn' %}" id="text-nav-oauth">Sign In</a>
                {% endif %}
            </div>
        </ul>
        </nav>
    </div>

    {% block content %}
    {% endblock %}
    
    {% block custom_scripts %}
    {% endblock custom_scripts %}

  
    </body>
</html>